[build]
nixpacksVersion = "1.38.0"

[phases.setup]
nixpkgs = ["python311", "nodejs_18", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmd = "python3 -m gunicorn siqnet_backend.wsgi"
