services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: siqnet_db
      POSTGRES_USER: siqnet_user
      POSTGRES_PASSWORD: siqnet_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
